<a href="https://colab.research.google.com/github/Nithiyasankar/NumPy_Tutorial_in_Python/blob/main/Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([])
print(np_array)
type(np_array)

[]


numpy.ndarray

In [ ]:
#creating a 1 dim array
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=str)
print(c)

[['1' '2' '3' '4']
 ['5' '6' '7' '8']]


In [ ]:
x= np.zeros((4,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z= np.full((4,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
c=np.random.randint(10,100,(3,5))
print(c)

[[30 72 37 26 13]
 [90 22 16 27 69]
 [73 45 87 24 75]]


In [ ]:
d=np.linspace(10,30,4)
print(d)

[10.         16.66666667 23.33333333 30.        ]


In [ ]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
e=np.arange(10,25,5)
print(e)

[10 15 20]


In [ ]:
list2=[10,20,30,40]
np_array=np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[34 61 81 73 45]
 [61 73 47 26 30]
 [87 78 39 55 24]
 [32 59 73 56 66]
 [72 83 70 32 48]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
print(c.ndim)

2


In [ ]:
print(c.dtype)

int64


In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 6 8]
 [0 3 1]
 [2 4 1]]
[[12 18 16]
 [16 10 12]
 [18 17 11]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[5 1 3]
 [2 0 3]
 [6 5 4]]
[[19 14 12]
 [17 12 19]
 [10 16 19]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[24 15 15]
 [19 12 22]
 [16 21 23]]
[[-14 -13  -9]
 [-15 -12 -16]
 [ -4 -11 -15]]
[[95 14 36]
 [34  0 57]
 [60 80 76]]
[[0.26315789 0.07142857 0.25      ]
 [0.11764706 0.         0.15789474]
 [0.6        0.3125     0.21052632]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[24 15 15]
 [19 12 22]
 [16 21 23]]
[[-14 -13  -9]
 [-15 -12 -16]
 [ -4 -11 -15]]
[[95 14 36]
 [34  0 57]
 [60 80 76]]
[[0.26315789 0.07142857 0.25      ]
 [0.11764706 0.         0.15789474]
 [0.6        0.3125     0.21052632]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 4 5]
 [7 7 3]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)

[[3 7]
 [4 7]
 [5 3]]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9])
print("First 5 element",array[:5])
print("Last 4 element",array[-4:])
print("Elements from index 2 to 6:",array[2:7])

First 5 element [1 2 3 4 5]
Last 4 element [6 7 8 9]
Elements from index 2 to 6: [3 4 5 6 7]


In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9])
reshaped_array = np.reshape(array, (3, 3))
print("Reshaped array:\n", reshaped_array)

Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
reshaped_array = np.reshape(array, (5, 5))
print("Reshaped array:\n", reshaped_array)

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
